import { version, repository } from '../../package.json';

export const CARD_VERSION = `v${version}`;
export const CARD_UPADE_SENSOR = 'update.vag_connect_card_update';
export const REPOSITORY = repository.url.replace('https://github.com/', '');

// VAG Connect Home Assistant integration domain — required for device-registry discovery
export const VAG_DOMAIN = 'vag_connect';

export const PREVIEW_CONFIG_TYPES = ['btn_preview', 'card_preview', 'tire_preview'];

/**
 * Entity filters mapped onto `unique_id` suffixes generated by the
 * VAG Connect integration. Pattern: `<VIN>_<translation_key>` — see
 * `custom_components/vag_connect/entity_base.py`.
 *
 * Each card item references one of these semantic keys; ha-helpers
 * resolves them to concrete entity_ids by scanning the VAG Connect
 * device's entities for a matching unique_id suffix.
 */
const binarySensorFilters: {
  [key: string]: { prefix?: string; suffix: string };
} = {
  doorsLocked: { suffix: '_doors_locked' },
  doorsOpen: { suffix: '_doors_open' },
  windowsOpen: { suffix: '_windows_open' },
  plugConnected: { suffix: '_plug_connected' },
  connectorLocked: { suffix: '_connector_locked' },
  isCharging: { suffix: '_is_charging' },
  isDriving: { suffix: '_is_driving' },
  isOnline: { suffix: '_is_online' },
  lightsOn: { suffix: '_lights_on' },
  climatisationActive: { suffix: '_climatisation_active' },
  windowHeatingEnabled: { suffix: '_window_heating_enabled' },
  windowHeatingFront: { suffix: '_window_heating_front' },
  windowHeatingBack: { suffix: '_window_heating_back' },
  batteryCareEnabled: { suffix: '_battery_care_enabled' },
  climateAtUnlock: { suffix: '_climate_at_unlock' },
  autoUnlockWhenCharged: { suffix: '_auto_unlock_when_charged' },
  otaUpdateAvailable: { suffix: '_ota_update_available' },
  warning12vLow: { suffix: '_warning_12v_low' },
  warningActive: { suffix: '_warning_active' },
  warningBrakes: { suffix: '_warning_brakes' },
  warningEngine: { suffix: '_warning_engine' },
  warningOil: { suffix: '_warning_oil' },
  warningTyre: { suffix: '_warning_tyre' },
};

const sensorFilters: {
  [key: string]: { prefix?: string; suffix: string };
} = {
  // Battery / Energy
  soc: { suffix: '_battery_soc' },
  targetSoc: { suffix: '_target_soc' },
  batteryCareTargetSoc: { suffix: '_battery_care_target_soc_pct' },
  chargingPower: { suffix: '_charging_power_kw' },
  chargingRate: { suffix: '_charging_rate_kmh' },
  chargeCompleteEta: { suffix: '_charge_complete_eta' },
  chargingType: { suffix: '_charging_type' },
  chargingState: { suffix: '_charging_state' },
  plugState: { suffix: '_plug_state' },
  maxChargeCurrent: { suffix: '_max_charge_current_a' },
  totalChargedEnergy: { suffix: '_total_charged_energy_kwh' },
  lastChargingSessionKwh: { suffix: '_last_charging_session_kwh' },
  lastChargingSessionDuration: { suffix: '_last_charging_session_duration_min' },
  activeChargingProfileName: { suffix: '_active_charging_profile_name' },
  activeChargingProfileTargetSoc: { suffix: '_active_charging_profile_target_soc_pct' },

  // Range / Fuel
  fuelLevel: { suffix: '_fuel_level' },
  adblueRange: { suffix: '_adblue_range_km' },
  rangeElectric: { suffix: '_electric_range_km' },
  rangeCombustion: { suffix: '_combustion_range_km' },
  rangeTotal: { suffix: '_total_range_km' },
  rangeLegacy: { suffix: '_range_km' },
  secondaryEngineRange: { suffix: '_secondary_engine_range_km' },

  // Position / Driving
  odometer: { suffix: '_odometer_km' },
  outsideTemp: { suffix: '_outside_temp' },
  batteryTemp: { suffix: '_battery_temp' },
  voltage12v: { suffix: '_voltage_12v' },
  vehicleState: { suffix: '_vehicle_state' },
  connectionState: { suffix: '_connection_state' },
  parkingAddress: { suffix: '_parking_address' },
  parkingCity: { suffix: '_parking_city' },

  // Climate
  climatisationState: { suffix: '_climatisation_state' },
  targetTemperature: { suffix: '_target_temperature' },

  // Service / Diagnostics
  serviceDueInDays: { suffix: '_service_due_in_days' },
  serviceDueAt: { suffix: '_service_due_at' },
  serviceKm: { suffix: '_service_km' },
  oilServiceDueInDays: { suffix: '_oil_service_due_in_days' },
  oilServiceAt: { suffix: '_oil_service_at' },
  oilServiceKm: { suffix: '_oil_service_km' },
  softwareVersion: { suffix: '_software_version' },
  licensePlate: { suffix: '_license_plate' },
  equipmentCount: { suffix: '_equipment_count' },
  capabilitiesCount: { suffix: '_capabilities_count' },
  lightsCount: { suffix: '_lights_count' },
  chargingProfilesCount: { suffix: '_charging_profiles_count' },
  requestsRemaining: { suffix: '_requests_remaining_today' },
  wakeCountToday: { suffix: '_wake_count_today' },
  lastUpdatedAt: { suffix: '_last_updated_at' },

  // Last Trip
  lastTripDistance: { suffix: '_last_trip_distance_km' },
  lastTripAvgSpeed: { suffix: '_last_trip_avg_speed_kmh' },
  lastTripAvgFuelConsumption: { suffix: '_last_trip_avg_fuel_consumption_l_100km' },
  lastTripAvgElectricConsumption: { suffix: '_last_trip_avg_electric_consumption_kwh_100km' },

  // Diagnostics observability
  apiObserverFindings: { suffix: '_api_observer_findings' },
  errorReporterCount: { suffix: '_error_reporter_count' },
};

export const combinedFilters = { ...binarySensorFilters, ...sensorFilters };

// Brand → device-registry manufacturer string mapping (lowercase comparison).
// Used by the header component to pick the right brand logo.
export const VAG_BRANDS = ['audi', 'volkswagen', 'skoda', 'seat', 'cupra', 'porsche', 'volkswagen_na'] as const;
export type VagBrand = (typeof VAG_BRANDS)[number];

// VAG Connect services exposed by the integration (custom_components/vag_connect/services.yaml).
// Used by the action-buttons row to invoke vehicle commands. Wake / refresh /
// flash / lock / unlock / climate / charging / window-heat / aux-heat /
// ventilation / engine-start-stop / set-target-soc / set-temp / set-timer.
export const VAG_SERVICES = {
  refresh: 'refresh_vehicle',
  refreshCache: 'refresh_cloud_cache',
  lock: 'lock',
  unlock: 'unlock',
  startClimate: 'start_climatisation',
  stopClimate: 'stop_climatisation',
  startCharging: 'start_charging',
  stopCharging: 'stop_charging',
  flashLights: 'flash_lights',
  startWindowHeating: 'start_window_heating',
  stopWindowHeating: 'stop_window_heating',
  startVentilation: 'start_ventilation',
  stopVentilation: 'stop_ventilation',
  startAuxHeating: 'start_aux_heating',
  stopAuxHeating: 'stop_aux_heating',
  wake: 'wake_vehicle',
  engineStart: 'engine_start',
  engineStop: 'engine_stop',
  setTargetSoc: 'set_target_soc',
  setClimateTemp: 'set_climatisation_temperature',
  setDepartureTimer: 'set_departure_timer',
  sendDestination: 'send_destination',
} as const;
